### ISSUE TITLE
I try to use the default settings and input images, but there is something wrong. Could you please give me some advice? 

### ISSUE THREAD

**Issue by cirolin** [woodrush/neural-art-tf#4]
$ python neural-art-tf.py 
Read images...
Traceback (most recent call last):
  File "neural-art-tf.py", line 12, in <module>
    content_image = read_image(content_image_path, width)
  File "/home/cirolin/neural-art-tf-master/utils.py", line 23, in read_image
    r = w / np.float32(img.shape[0])
IndexError: tuple index out of range

**Comment by clawtros** [comment]
You might not have libjpeg installed, so read_image could come back with an empty thing -- try it with PNGs?

**Comment by liunuozhi** [comment]
I think I got the same problem, but still cannot deal with it.

python neural-art-tf.py -m vgg -c ./images/sd.jpg -s ./images/style.jpg -w 800
Read images...
Traceback (most recent call last):
  File "neural-art-tf.py", line 12, in <module>
    content_image = read_image(content_image_path, width)
  File "/home/ronnie/neural-art-tf/utils.py", line 20, in read_image
    img = scipy.misc.imread(path)
AttributeError: 'module' object has no attribute 'imread'
