### ISSUE TITLE
AttributeError: Can't pickle local object 'CaffeDataReader.dump.<locals>.convert'

### ISSUE THREAD

**Issue by Jermmy** [woodrush/neural-art-tf#7]
I install caffe and tensorflow for python3.5, and run the kaffe.py to convert data. However, it throws an error when saving data.
```Traceback (most recent call last):
  File "kaffe/kaffe.py", line 109, in <module>
    main()
  File "kaffe/kaffe.py", line 106, in main
    CaffeDataReader(def_path, data_path).dump(dst_path)
  File "kaffe/kaffe.py", line 97, in dump
    np.save(open(dst_path, 'wb'), dict(params))
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 509, in save
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/format.py", line 576, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
AttributeError: Can't pickle local object 'CaffeDataReader.dump.<locals>.convert'
``` 
How should I fix it?

**Comment by Jermmy** [comment]
Well, finally I cast the map to list and solved it.

**Comment by scalfs** [comment]
I'm having the same problem, Jermmy. Can you explain how you solved it, please?

**Comment by Jermmy** [comment]
I just made some type conversion to support python3. Maybe you can check my [modification](https://github.com/Jermmy/neural_art_tf/blob/master/kaffe/kaffe.py) for detail.

**Comment by scalfs** [comment]
Awesome! Thanks, man.
